-- 데이터베이스 스키마

-- 데이터베이스 생성
CREATE DATABASE IF NOT EXISTS your_database_name
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_general_ci;

USE your_database_name;

-- 환경 데이터 테이블
CREATE TABLE IF NOT EXISTS GROWING_ENVIRONMENT (
    TEMPER_NUM INT PRIMARY KEY AUTO_INCREMENT,
    TEMPER FLOAT NOT NULL,
    HUMIDITY FLOAT NOT NULL,
    SOIL_HUMIDITY FLOAT NOT NULL,
    ILLUMINATION INT NOT NULL,
    CREATE_DATE DATETIME DEFAULT SYSDATE()
);

-- 제어 상태 테이블
CREATE TABLE IF NOT EXISTS DEVICE_STATUS (
    STATUS_ID INT PRIMARY KEY AUTO_INCREMENT,
    TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
    MOTION_DETECTED TINYINT(1) DEFAULT 0,
    FAN_MOTOR TINYINT(1) DEFAULT 0,
    WATER_PUMP TINYINT(1) DEFAULT 0,
    LED_LIGHT TINYINT(1) DEFAULT 0
);

-- 인덱스 생성 (조회 성능 향상)
CREATE INDEX idx_measure_time ON GROWING_ENVIRONMENT(CREATE_DATE);
CREATE INDEX idx_record_time ON DEVICE_STATUS(TIMESTAMP);

-- 테이블 구조 확인
SHOW TABLES;
DESC GROWING_ENVIRONMENT;
DESC DEVICE_STATUS;